run: 
	python manage.py runserver --settings=settings.local

#migrate

migrate:
	python manage.py migrate --settings=settings.local

# makemigrations

makemigratios:
	python manage.py makemigrations --settings=settings.local


# hacemos otro para produccion

run-prod:
	python manage.py runserver --settings=settings.prod

