# Generated by Django 4.1.6 on 2023-02-08 11:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="indexApp/images")),
                (
                    "created_day",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2023, 2, 8, 11, 34, 51, 383183, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                ("published_day", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
