# Generated by Django 4.1.6 on 2023-02-08 11:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("indexApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="created_day",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
